In [20]:
import pandas as pd
import numpy as np
from sklearn.naive_bayes import GaussianNB
from sklearn.model_selection import KFold
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

names = ['sepal-length','sepal-width','petal-length','petal-width','class'];
dataset = pd.read_csv("G:\\UIT BS-SE Semester-VI Course Folders\\CS 321 - Artificial Intelligence\\Lab\\A.I. Lab 09\\iris.data",names=names);

array = dataset.values;
X = array[:,0:4]
Y = array[:,4]

X_train, X_test, Y_train, Y_test = train_test_split(X,Y,test_size=0.3,random_state=12)
model = GaussianNB()
model.fit(X,Y)
predicted = model.predict(X_test)
print("\nPredicted Value for 30:70 Split:", predicted)
print("\nAccuracy Score for 30:70 Split:",accuracy_score(Y_test, predicted))
print(confusion_matrix(Y_test, predicted))
print(classification_report(Y_test, predicted))

X_train, X_test, Y_train, Y_test = train_test_split(X,Y,test_size=0.6,random_state=56)
model = GaussianNB()
model.fit(X,Y)
predicted = model.predict(X_test)
print("\nPredicted Value for 60:40 Split:", predicted)
print("\nAccuracy Score for 60:40 Split:",accuracy_score(Y_test, predicted))
print(confusion_matrix(Y_test, predicted))
print(classification_report(Y_test, predicted))

X_train, X_test, Y_train, Y_test = train_test_split(X,Y,test_size=0.7,random_state=79)
model = GaussianNB()
model.fit(X,Y)
predicted = model.predict(X_test)
print("\nPredicted Value for 70:30 Split:", predicted)
print("\nAccuracy Score for 70:30 Split:",accuracy_score(Y_test, predicted))
print(confusion_matrix(Y_test, predicted))
print(classification_report(Y_test, predicted))

X_train, X_test, Y_train, Y_test = train_test_split(X,Y,test_size=0.8,random_state=115)
model = GaussianNB()
model.fit(X,Y)
predicted = model.predict(X_test)
print("\nPredicted Value for 80:20 Split:", predicted)
print("\nAccuracy Score for 80:20 Split:",accuracy_score(Y_test, predicted))
print(confusion_matrix(Y_test, predicted))
print(classification_report(Y_test, predicted))

kfold = KFold(5, True, 1)
for train, test in kfold.split(dataset):
    print('X_train: %s, X_test: %s' % (X_train, X_test))
    print('Y_train: %s, Y_test: %s' % (Y_train, Y_test))
   




Predicted Value for 30:70 Split: ['Iris-setosa' 'Iris-virginica' 'Iris-setosa' 'Iris-versicolor'
 'Iris-virginica' 'Iris-virginica' 'Iris-virginica' 'Iris-setosa'
 'Iris-virginica' 'Iris-setosa' 'Iris-versicolor' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-versicolor' 'Iris-virginica'
 'Iris-virginica' 'Iris-versicolor' 'Iris-setosa' 'Iris-versicolor'
 'Iris-setosa' 'Iris-versicolor' 'Iris-virginica' 'Iris-versicolor'
 'Iris-setosa' 'Iris-virginica' 'Iris-virginica' 'Iris-versicolor'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-versicolor'
 'Iris-virginica' 'Iris-setosa' 'Iris-virginica' 'Iris-setosa'
 'Iris-versicolor' 'Iris-versicolor' 'Iris-setosa' 'Iris-versicolor'
 'Iris-versicolor' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa']

Accuracy Score for 30:70 Split: 0.9777777777777777
[[20  0  0]
 [ 0 13  1]
 [ 0  0 11]]
                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        20
Iris-versicolor       1.00      