In [1]:
import numpy as np

# sigmoid function
def nonlin(x,deriv=False):
    if(deriv==True):
        return x*(1-x)
    return 1/(1+np.exp(-x))

# input dataset
X = np.array([  [0,0,1],
                [0,1,1],
                [1,0,1],
                [1,1,1] ])
#output dataset
y = np.array([[0,1,1,0]]).T

# seed random numbers to make calculation 
# deterministic (just a good practice) 
np.random.seed(1) 

# initialize weights randomly with mean 0
syn0 = np.random.random((3,1))
for iter in range (10000):
    #forward propagation
    l0 = X
    l1 = nonlin(np.dot(l0,syn0))
    #how much did we miss?
    l1_error = y - l1
    #multiply how much we missed by the
    #slope of the sigmoid at the values in 11
    l1_delta = l1_error * nonlin(l1,True)
    #update weights
    syn0 += np.dot(l0.T,l1_delta)
    
    print ("Output After Training:")
    print (l1) 

Output After Training:
[[0.50002859]
 [0.67270365]
 [0.60279781]
 [0.75721315]]
Output After Training:
[[0.47578526]
 [0.63558316]
 [0.56856119]
 [0.71690537]]
Output After Training:
[[0.45738795]
 [0.60377622]
 [0.54050843]
 [0.68015338]]
Output After Training:
[[0.44437243]
 [0.57822155]
 [0.51898391]
 [0.64905417]]
Output After Training:
[[0.43584261]
 [0.55869823]
 [0.50339809]
 [0.62422614]]
Output After Training:
[[0.43077437]
 [0.54428906]
 [0.49266891]
 [0.60515414]]
Output After Training:
[[0.42822925]
 [0.53386594]
 [0.4856277 ]
 [0.59079332]]
Output After Training:
[[0.4274474 ]
 [0.52638754]
 [0.48124872]
 [0.5800263 ]]
Output After Training:
[[0.42785738]
 [0.52101378]
 [0.47872488]
 [0.57188624]]
Output After Training:
[[0.4290485 ]
 [0.51711519]
 [0.47745998]
 [0.56561947]]
Output After Training:
[[0.43073411]
 [0.51424004]
 [0.47703033]
 [0.56067176]]
Output After Training:
[[0.43271815]
 [0.51207264]
 [0.47714244]
 [0.55664962]]
Output After Training:
[[0.43486858]
 [0

 [0.50000187]]
Output After Training:
[[0.49999738]
 [0.49999959]
 [0.49999959]
 [0.5000018 ]]
Output After Training:
[[0.49999748]
 [0.49999961]
 [0.4999996 ]
 [0.50000173]]
Output After Training:
[[0.49999758]
 [0.49999962]
 [0.49999962]
 [0.50000166]]
Output After Training:
[[0.49999767]
 [0.49999964]
 [0.49999963]
 [0.5000016 ]]
Output After Training:
[[0.49999776]
 [0.49999965]
 [0.49999965]
 [0.50000153]]
Output After Training:
[[0.49999785]
 [0.49999966]
 [0.49999966]
 [0.50000147]]
Output After Training:
[[0.49999794]
 [0.49999968]
 [0.49999968]
 [0.50000142]]
Output After Training:
[[0.49999802]
 [0.49999969]
 [0.49999969]
 [0.50000136]]
Output After Training:
[[0.4999981 ]
 [0.4999997 ]
 [0.4999997 ]
 [0.50000131]]
Output After Training:
[[0.49999817]
 [0.49999971]
 [0.49999971]
 [0.50000126]]
Output After Training:
[[0.49999824]
 [0.49999972]
 [0.49999972]
 [0.50000121]]
Output After Training:
[[0.49999831]
 [0.49999974]
 [0.49999973]
 [0.50000116]]
Output After Training:
[[

 [0.5]]
Output After Training:
[[0.5]
 [0.5]
 [0.5]
 [0.5]]
Output After Training:
[[0.5]
 [0.5]
 [0.5]
 [0.5]]
Output After Training:
[[0.5]
 [0.5]
 [0.5]
 [0.5]]
Output After Training:
[[0.5]
 [0.5]
 [0.5]
 [0.5]]
Output After Training:
[[0.5]
 [0.5]
 [0.5]
 [0.5]]
Output After Training:
[[0.5]
 [0.5]
 [0.5]
 [0.5]]
Output After Training:
[[0.5]
 [0.5]
 [0.5]
 [0.5]]
Output After Training:
[[0.5]
 [0.5]
 [0.5]
 [0.5]]
Output After Training:
[[0.5]
 [0.5]
 [0.5]
 [0.5]]
Output After Training:
[[0.5]
 [0.5]
 [0.5]
 [0.5]]
Output After Training:
[[0.5]
 [0.5]
 [0.5]
 [0.5]]
Output After Training:
[[0.5]
 [0.5]
 [0.5]
 [0.5]]
Output After Training:
[[0.5]
 [0.5]
 [0.5]
 [0.5]]
Output After Training:
[[0.5]
 [0.5]
 [0.5]
 [0.5]]
Output After Training:
[[0.5]
 [0.5]
 [0.5]
 [0.5]]
Output After Training:
[[0.5]
 [0.5]
 [0.5]
 [0.5]]
Output After Training:
[[0.5]
 [0.5]
 [0.5]
 [0.5]]
Output After Training:
[[0.5]
 [0.5]
 [0.5]
 [0.5]]
Output After Training:
[[0.5]
 [0.5]
 [0.5]
 [0.5]]
Outp

Output After Training:
[[0.5]
 [0.5]
 [0.5]
 [0.5]]
Output After Training:
[[0.5]
 [0.5]
 [0.5]
 [0.5]]
Output After Training:
[[0.5]
 [0.5]
 [0.5]
 [0.5]]
Output After Training:
[[0.5]
 [0.5]
 [0.5]
 [0.5]]
Output After Training:
[[0.5]
 [0.5]
 [0.5]
 [0.5]]
Output After Training:
[[0.5]
 [0.5]
 [0.5]
 [0.5]]
Output After Training:
[[0.5]
 [0.5]
 [0.5]
 [0.5]]
Output After Training:
[[0.5]
 [0.5]
 [0.5]
 [0.5]]
Output After Training:
[[0.5]
 [0.5]
 [0.5]
 [0.5]]
Output After Training:
[[0.5]
 [0.5]
 [0.5]
 [0.5]]
Output After Training:
[[0.5]
 [0.5]
 [0.5]
 [0.5]]
Output After Training:
[[0.5]
 [0.5]
 [0.5]
 [0.5]]
Output After Training:
[[0.5]
 [0.5]
 [0.5]
 [0.5]]
Output After Training:
[[0.5]
 [0.5]
 [0.5]
 [0.5]]
Output After Training:
[[0.5]
 [0.5]
 [0.5]
 [0.5]]
Output After Training:
[[0.5]
 [0.5]
 [0.5]
 [0.5]]
Output After Training:
[[0.5]
 [0.5]
 [0.5]
 [0.5]]
Output After Training:
[[0.5]
 [0.5]
 [0.5]
 [0.5]]
Output After Training:
[[0.5]
 [0.5]
 [0.5]
 [0.5]]
Output After

[[0.5]
 [0.5]
 [0.5]
 [0.5]]
Output After Training:
[[0.5]
 [0.5]
 [0.5]
 [0.5]]
Output After Training:
[[0.5]
 [0.5]
 [0.5]
 [0.5]]
Output After Training:
[[0.5]
 [0.5]
 [0.5]
 [0.5]]
Output After Training:
[[0.5]
 [0.5]
 [0.5]
 [0.5]]
Output After Training:
[[0.5]
 [0.5]
 [0.5]
 [0.5]]
Output After Training:
[[0.5]
 [0.5]
 [0.5]
 [0.5]]
Output After Training:
[[0.5]
 [0.5]
 [0.5]
 [0.5]]
Output After Training:
[[0.5]
 [0.5]
 [0.5]
 [0.5]]
Output After Training:
[[0.5]
 [0.5]
 [0.5]
 [0.5]]
Output After Training:
[[0.5]
 [0.5]
 [0.5]
 [0.5]]
Output After Training:
[[0.5]
 [0.5]
 [0.5]
 [0.5]]
Output After Training:
[[0.5]
 [0.5]
 [0.5]
 [0.5]]
Output After Training:
[[0.5]
 [0.5]
 [0.5]
 [0.5]]
Output After Training:
[[0.5]
 [0.5]
 [0.5]
 [0.5]]
Output After Training:
[[0.5]
 [0.5]
 [0.5]
 [0.5]]
Output After Training:
[[0.5]
 [0.5]
 [0.5]
 [0.5]]
Output After Training:
[[0.5]
 [0.5]
 [0.5]
 [0.5]]
Output After Training:
[[0.5]
 [0.5]
 [0.5]
 [0.5]]
Output After Training:
[[0.5]
 [0.5

 [0.5]]
Output After Training:
[[0.5]
 [0.5]
 [0.5]
 [0.5]]
Output After Training:
[[0.5]
 [0.5]
 [0.5]
 [0.5]]
Output After Training:
[[0.5]
 [0.5]
 [0.5]
 [0.5]]
Output After Training:
[[0.5]
 [0.5]
 [0.5]
 [0.5]]
Output After Training:
[[0.5]
 [0.5]
 [0.5]
 [0.5]]
Output After Training:
[[0.5]
 [0.5]
 [0.5]
 [0.5]]
Output After Training:
[[0.5]
 [0.5]
 [0.5]
 [0.5]]
Output After Training:
[[0.5]
 [0.5]
 [0.5]
 [0.5]]
Output After Training:
[[0.5]
 [0.5]
 [0.5]
 [0.5]]
Output After Training:
[[0.5]
 [0.5]
 [0.5]
 [0.5]]
Output After Training:
[[0.5]
 [0.5]
 [0.5]
 [0.5]]
Output After Training:
[[0.5]
 [0.5]
 [0.5]
 [0.5]]
Output After Training:
[[0.5]
 [0.5]
 [0.5]
 [0.5]]
Output After Training:
[[0.5]
 [0.5]
 [0.5]
 [0.5]]
Output After Training:
[[0.5]
 [0.5]
 [0.5]
 [0.5]]
Output After Training:
[[0.5]
 [0.5]
 [0.5]
 [0.5]]
Output After Training:
[[0.5]
 [0.5]
 [0.5]
 [0.5]]
Output After Training:
[[0.5]
 [0.5]
 [0.5]
 [0.5]]
Output After Training:
[[0.5]
 [0.5]
 [0.5]
 [0.5]]
Outp

Output After Training:
[[0.5]
 [0.5]
 [0.5]
 [0.5]]
Output After Training:
[[0.5]
 [0.5]
 [0.5]
 [0.5]]
Output After Training:
[[0.5]
 [0.5]
 [0.5]
 [0.5]]
Output After Training:
[[0.5]
 [0.5]
 [0.5]
 [0.5]]
Output After Training:
[[0.5]
 [0.5]
 [0.5]
 [0.5]]
Output After Training:
[[0.5]
 [0.5]
 [0.5]
 [0.5]]
Output After Training:
[[0.5]
 [0.5]
 [0.5]
 [0.5]]
Output After Training:
[[0.5]
 [0.5]
 [0.5]
 [0.5]]
Output After Training:
[[0.5]
 [0.5]
 [0.5]
 [0.5]]
Output After Training:
[[0.5]
 [0.5]
 [0.5]
 [0.5]]
Output After Training:
[[0.5]
 [0.5]
 [0.5]
 [0.5]]
Output After Training:
[[0.5]
 [0.5]
 [0.5]
 [0.5]]
Output After Training:
[[0.5]
 [0.5]
 [0.5]
 [0.5]]
Output After Training:
[[0.5]
 [0.5]
 [0.5]
 [0.5]]
Output After Training:
[[0.5]
 [0.5]
 [0.5]
 [0.5]]
Output After Training:
[[0.5]
 [0.5]
 [0.5]
 [0.5]]
Output After Training:
[[0.5]
 [0.5]
 [0.5]
 [0.5]]
Output After Training:
[[0.5]
 [0.5]
 [0.5]
 [0.5]]
Output After Training:
[[0.5]
 [0.5]
 [0.5]
 [0.5]]
Output After

 [0.5]]
Output After Training:
[[0.5]
 [0.5]
 [0.5]
 [0.5]]
Output After Training:
[[0.5]
 [0.5]
 [0.5]
 [0.5]]
Output After Training:
[[0.5]
 [0.5]
 [0.5]
 [0.5]]
Output After Training:
[[0.5]
 [0.5]
 [0.5]
 [0.5]]
Output After Training:
[[0.5]
 [0.5]
 [0.5]
 [0.5]]
Output After Training:
[[0.5]
 [0.5]
 [0.5]
 [0.5]]
Output After Training:
[[0.5]
 [0.5]
 [0.5]
 [0.5]]
Output After Training:
[[0.5]
 [0.5]
 [0.5]
 [0.5]]
Output After Training:
[[0.5]
 [0.5]
 [0.5]
 [0.5]]
Output After Training:
[[0.5]
 [0.5]
 [0.5]
 [0.5]]
Output After Training:
[[0.5]
 [0.5]
 [0.5]
 [0.5]]
Output After Training:
[[0.5]
 [0.5]
 [0.5]
 [0.5]]
Output After Training:
[[0.5]
 [0.5]
 [0.5]
 [0.5]]
Output After Training:
[[0.5]
 [0.5]
 [0.5]
 [0.5]]
Output After Training:
[[0.5]
 [0.5]
 [0.5]
 [0.5]]
Output After Training:
[[0.5]
 [0.5]
 [0.5]
 [0.5]]
Output After Training:
[[0.5]
 [0.5]
 [0.5]
 [0.5]]
Output After Training:
[[0.5]
 [0.5]
 [0.5]
 [0.5]]
Output After Training:
[[0.5]
 [0.5]
 [0.5]
 [0.5]]
Outp

Output After Training:
[[0.5]
 [0.5]
 [0.5]
 [0.5]]
Output After Training:
[[0.5]
 [0.5]
 [0.5]
 [0.5]]
Output After Training:
[[0.5]
 [0.5]
 [0.5]
 [0.5]]
Output After Training:
[[0.5]
 [0.5]
 [0.5]
 [0.5]]
Output After Training:
[[0.5]
 [0.5]
 [0.5]
 [0.5]]
Output After Training:
[[0.5]
 [0.5]
 [0.5]
 [0.5]]
Output After Training:
[[0.5]
 [0.5]
 [0.5]
 [0.5]]
Output After Training:
[[0.5]
 [0.5]
 [0.5]
 [0.5]]
Output After Training:
[[0.5]
 [0.5]
 [0.5]
 [0.5]]
Output After Training:
[[0.5]
 [0.5]
 [0.5]
 [0.5]]
Output After Training:
[[0.5]
 [0.5]
 [0.5]
 [0.5]]
Output After Training:
[[0.5]
 [0.5]
 [0.5]
 [0.5]]
Output After Training:
[[0.5]
 [0.5]
 [0.5]
 [0.5]]
Output After Training:
[[0.5]
 [0.5]
 [0.5]
 [0.5]]
Output After Training:
[[0.5]
 [0.5]
 [0.5]
 [0.5]]
Output After Training:
[[0.5]
 [0.5]
 [0.5]
 [0.5]]
Output After Training:
[[0.5]
 [0.5]
 [0.5]
 [0.5]]
Output After Training:
[[0.5]
 [0.5]
 [0.5]
 [0.5]]
Output After Training:
[[0.5]
 [0.5]
 [0.5]
 [0.5]]
Output After

Output After Training:
[[0.5]
 [0.5]
 [0.5]
 [0.5]]
Output After Training:
[[0.5]
 [0.5]
 [0.5]
 [0.5]]
Output After Training:
[[0.5]
 [0.5]
 [0.5]
 [0.5]]
Output After Training:
[[0.5]
 [0.5]
 [0.5]
 [0.5]]
Output After Training:
[[0.5]
 [0.5]
 [0.5]
 [0.5]]
Output After Training:
[[0.5]
 [0.5]
 [0.5]
 [0.5]]
Output After Training:
[[0.5]
 [0.5]
 [0.5]
 [0.5]]
Output After Training:
[[0.5]
 [0.5]
 [0.5]
 [0.5]]
Output After Training:
[[0.5]
 [0.5]
 [0.5]
 [0.5]]
Output After Training:
[[0.5]
 [0.5]
 [0.5]
 [0.5]]
Output After Training:
[[0.5]
 [0.5]
 [0.5]
 [0.5]]
Output After Training:
[[0.5]
 [0.5]
 [0.5]
 [0.5]]
Output After Training:
[[0.5]
 [0.5]
 [0.5]
 [0.5]]
Output After Training:
[[0.5]
 [0.5]
 [0.5]
 [0.5]]
Output After Training:
[[0.5]
 [0.5]
 [0.5]
 [0.5]]
Output After Training:
[[0.5]
 [0.5]
 [0.5]
 [0.5]]
Output After Training:
[[0.5]
 [0.5]
 [0.5]
 [0.5]]
Output After Training:
[[0.5]
 [0.5]
 [0.5]
 [0.5]]
Output After Training:
[[0.5]
 [0.5]
 [0.5]
 [0.5]]
Output After

 [0.5]]
Output After Training:
[[0.5]
 [0.5]
 [0.5]
 [0.5]]
Output After Training:
[[0.5]
 [0.5]
 [0.5]
 [0.5]]
Output After Training:
[[0.5]
 [0.5]
 [0.5]
 [0.5]]
Output After Training:
[[0.5]
 [0.5]
 [0.5]
 [0.5]]
Output After Training:
[[0.5]
 [0.5]
 [0.5]
 [0.5]]
Output After Training:
[[0.5]
 [0.5]
 [0.5]
 [0.5]]
Output After Training:
[[0.5]
 [0.5]
 [0.5]
 [0.5]]
Output After Training:
[[0.5]
 [0.5]
 [0.5]
 [0.5]]
Output After Training:
[[0.5]
 [0.5]
 [0.5]
 [0.5]]
Output After Training:
[[0.5]
 [0.5]
 [0.5]
 [0.5]]
Output After Training:
[[0.5]
 [0.5]
 [0.5]
 [0.5]]
Output After Training:
[[0.5]
 [0.5]
 [0.5]
 [0.5]]
Output After Training:
[[0.5]
 [0.5]
 [0.5]
 [0.5]]
Output After Training:
[[0.5]
 [0.5]
 [0.5]
 [0.5]]
Output After Training:
[[0.5]
 [0.5]
 [0.5]
 [0.5]]
Output After Training:
[[0.5]
 [0.5]
 [0.5]
 [0.5]]
Output After Training:
[[0.5]
 [0.5]
 [0.5]
 [0.5]]
Output After Training:
[[0.5]
 [0.5]
 [0.5]
 [0.5]]
Output After Training:
[[0.5]
 [0.5]
 [0.5]
 [0.5]]
Outp

 [0.5]]
Output After Training:
[[0.5]
 [0.5]
 [0.5]
 [0.5]]
Output After Training:
[[0.5]
 [0.5]
 [0.5]
 [0.5]]
Output After Training:
[[0.5]
 [0.5]
 [0.5]
 [0.5]]
Output After Training:
[[0.5]
 [0.5]
 [0.5]
 [0.5]]
Output After Training:
[[0.5]
 [0.5]
 [0.5]
 [0.5]]
Output After Training:
[[0.5]
 [0.5]
 [0.5]
 [0.5]]
Output After Training:
[[0.5]
 [0.5]
 [0.5]
 [0.5]]
Output After Training:
[[0.5]
 [0.5]
 [0.5]
 [0.5]]
Output After Training:
[[0.5]
 [0.5]
 [0.5]
 [0.5]]
Output After Training:
[[0.5]
 [0.5]
 [0.5]
 [0.5]]
Output After Training:
[[0.5]
 [0.5]
 [0.5]
 [0.5]]
Output After Training:
[[0.5]
 [0.5]
 [0.5]
 [0.5]]
Output After Training:
[[0.5]
 [0.5]
 [0.5]
 [0.5]]
Output After Training:
[[0.5]
 [0.5]
 [0.5]
 [0.5]]
Output After Training:
[[0.5]
 [0.5]
 [0.5]
 [0.5]]
Output After Training:
[[0.5]
 [0.5]
 [0.5]
 [0.5]]
Output After Training:
[[0.5]
 [0.5]
 [0.5]
 [0.5]]
Output After Training:
[[0.5]
 [0.5]
 [0.5]
 [0.5]]
Output After Training:
[[0.5]
 [0.5]
 [0.5]
 [0.5]]
Outp

Output After Training:
[[0.5]
 [0.5]
 [0.5]
 [0.5]]
Output After Training:
[[0.5]
 [0.5]
 [0.5]
 [0.5]]
Output After Training:
[[0.5]
 [0.5]
 [0.5]
 [0.5]]
Output After Training:
[[0.5]
 [0.5]
 [0.5]
 [0.5]]
Output After Training:
[[0.5]
 [0.5]
 [0.5]
 [0.5]]
Output After Training:
[[0.5]
 [0.5]
 [0.5]
 [0.5]]
Output After Training:
[[0.5]
 [0.5]
 [0.5]
 [0.5]]
Output After Training:
[[0.5]
 [0.5]
 [0.5]
 [0.5]]
Output After Training:
[[0.5]
 [0.5]
 [0.5]
 [0.5]]
Output After Training:
[[0.5]
 [0.5]
 [0.5]
 [0.5]]
Output After Training:
[[0.5]
 [0.5]
 [0.5]
 [0.5]]
Output After Training:
[[0.5]
 [0.5]
 [0.5]
 [0.5]]
Output After Training:
[[0.5]
 [0.5]
 [0.5]
 [0.5]]
Output After Training:
[[0.5]
 [0.5]
 [0.5]
 [0.5]]
Output After Training:
[[0.5]
 [0.5]
 [0.5]
 [0.5]]
Output After Training:
[[0.5]
 [0.5]
 [0.5]
 [0.5]]
Output After Training:
[[0.5]
 [0.5]
 [0.5]
 [0.5]]
Output After Training:
[[0.5]
 [0.5]
 [0.5]
 [0.5]]
Output After Training:
[[0.5]
 [0.5]
 [0.5]
 [0.5]]
Output After

[[0.5]
 [0.5]
 [0.5]
 [0.5]]
Output After Training:
[[0.5]
 [0.5]
 [0.5]
 [0.5]]
Output After Training:
[[0.5]
 [0.5]
 [0.5]
 [0.5]]
Output After Training:
[[0.5]
 [0.5]
 [0.5]
 [0.5]]
Output After Training:
[[0.5]
 [0.5]
 [0.5]
 [0.5]]
Output After Training:
[[0.5]
 [0.5]
 [0.5]
 [0.5]]
Output After Training:
[[0.5]
 [0.5]
 [0.5]
 [0.5]]
Output After Training:
[[0.5]
 [0.5]
 [0.5]
 [0.5]]
Output After Training:
[[0.5]
 [0.5]
 [0.5]
 [0.5]]
Output After Training:
[[0.5]
 [0.5]
 [0.5]
 [0.5]]
Output After Training:
[[0.5]
 [0.5]
 [0.5]
 [0.5]]
Output After Training:
[[0.5]
 [0.5]
 [0.5]
 [0.5]]
Output After Training:
[[0.5]
 [0.5]
 [0.5]
 [0.5]]
Output After Training:
[[0.5]
 [0.5]
 [0.5]
 [0.5]]
Output After Training:
[[0.5]
 [0.5]
 [0.5]
 [0.5]]
Output After Training:
[[0.5]
 [0.5]
 [0.5]
 [0.5]]
Output After Training:
[[0.5]
 [0.5]
 [0.5]
 [0.5]]
Output After Training:
[[0.5]
 [0.5]
 [0.5]
 [0.5]]
Output After Training:
[[0.5]
 [0.5]
 [0.5]
 [0.5]]
Output After Training:
[[0.5]
 [0.5

[[0.5]
 [0.5]
 [0.5]
 [0.5]]
Output After Training:
[[0.5]
 [0.5]
 [0.5]
 [0.5]]
Output After Training:
[[0.5]
 [0.5]
 [0.5]
 [0.5]]
Output After Training:
[[0.5]
 [0.5]
 [0.5]
 [0.5]]
Output After Training:
[[0.5]
 [0.5]
 [0.5]
 [0.5]]
Output After Training:
[[0.5]
 [0.5]
 [0.5]
 [0.5]]
Output After Training:
[[0.5]
 [0.5]
 [0.5]
 [0.5]]
Output After Training:
[[0.5]
 [0.5]
 [0.5]
 [0.5]]
Output After Training:
[[0.5]
 [0.5]
 [0.5]
 [0.5]]
Output After Training:
[[0.5]
 [0.5]
 [0.5]
 [0.5]]
Output After Training:
[[0.5]
 [0.5]
 [0.5]
 [0.5]]
Output After Training:
[[0.5]
 [0.5]
 [0.5]
 [0.5]]
Output After Training:
[[0.5]
 [0.5]
 [0.5]
 [0.5]]
Output After Training:
[[0.5]
 [0.5]
 [0.5]
 [0.5]]
Output After Training:
[[0.5]
 [0.5]
 [0.5]
 [0.5]]
Output After Training:
[[0.5]
 [0.5]
 [0.5]
 [0.5]]
Output After Training:
[[0.5]
 [0.5]
 [0.5]
 [0.5]]
Output After Training:
[[0.5]
 [0.5]
 [0.5]
 [0.5]]
Output After Training:
[[0.5]
 [0.5]
 [0.5]
 [0.5]]
Output After Training:
[[0.5]
 [0.5

[[0.5]
 [0.5]
 [0.5]
 [0.5]]
Output After Training:
[[0.5]
 [0.5]
 [0.5]
 [0.5]]
Output After Training:
[[0.5]
 [0.5]
 [0.5]
 [0.5]]
Output After Training:
[[0.5]
 [0.5]
 [0.5]
 [0.5]]
Output After Training:
[[0.5]
 [0.5]
 [0.5]
 [0.5]]
Output After Training:
[[0.5]
 [0.5]
 [0.5]
 [0.5]]
Output After Training:
[[0.5]
 [0.5]
 [0.5]
 [0.5]]
Output After Training:
[[0.5]
 [0.5]
 [0.5]
 [0.5]]
Output After Training:
[[0.5]
 [0.5]
 [0.5]
 [0.5]]
Output After Training:
[[0.5]
 [0.5]
 [0.5]
 [0.5]]
Output After Training:
[[0.5]
 [0.5]
 [0.5]
 [0.5]]
Output After Training:
[[0.5]
 [0.5]
 [0.5]
 [0.5]]
Output After Training:
[[0.5]
 [0.5]
 [0.5]
 [0.5]]
Output After Training:
[[0.5]
 [0.5]
 [0.5]
 [0.5]]
Output After Training:
[[0.5]
 [0.5]
 [0.5]
 [0.5]]
Output After Training:
[[0.5]
 [0.5]
 [0.5]
 [0.5]]
Output After Training:
[[0.5]
 [0.5]
 [0.5]
 [0.5]]
Output After Training:
[[0.5]
 [0.5]
 [0.5]
 [0.5]]
Output After Training:
[[0.5]
 [0.5]
 [0.5]
 [0.5]]
Output After Training:
[[0.5]
 [0.5

Output After Training:
[[0.5]
 [0.5]
 [0.5]
 [0.5]]
Output After Training:
[[0.5]
 [0.5]
 [0.5]
 [0.5]]
Output After Training:
[[0.5]
 [0.5]
 [0.5]
 [0.5]]
Output After Training:
[[0.5]
 [0.5]
 [0.5]
 [0.5]]
Output After Training:
[[0.5]
 [0.5]
 [0.5]
 [0.5]]
Output After Training:
[[0.5]
 [0.5]
 [0.5]
 [0.5]]
Output After Training:
[[0.5]
 [0.5]
 [0.5]
 [0.5]]
Output After Training:
[[0.5]
 [0.5]
 [0.5]
 [0.5]]
Output After Training:
[[0.5]
 [0.5]
 [0.5]
 [0.5]]
Output After Training:
[[0.5]
 [0.5]
 [0.5]
 [0.5]]
Output After Training:
[[0.5]
 [0.5]
 [0.5]
 [0.5]]
Output After Training:
[[0.5]
 [0.5]
 [0.5]
 [0.5]]
Output After Training:
[[0.5]
 [0.5]
 [0.5]
 [0.5]]
Output After Training:
[[0.5]
 [0.5]
 [0.5]
 [0.5]]
Output After Training:
[[0.5]
 [0.5]
 [0.5]
 [0.5]]
Output After Training:
[[0.5]
 [0.5]
 [0.5]
 [0.5]]
Output After Training:
[[0.5]
 [0.5]
 [0.5]
 [0.5]]
Output After Training:
[[0.5]
 [0.5]
 [0.5]
 [0.5]]
Output After Training:
[[0.5]
 [0.5]
 [0.5]
 [0.5]]
Output After

Output After Training:
[[0.5]
 [0.5]
 [0.5]
 [0.5]]
Output After Training:
[[0.5]
 [0.5]
 [0.5]
 [0.5]]
Output After Training:
[[0.5]
 [0.5]
 [0.5]
 [0.5]]
Output After Training:
[[0.5]
 [0.5]
 [0.5]
 [0.5]]
Output After Training:
[[0.5]
 [0.5]
 [0.5]
 [0.5]]
Output After Training:
[[0.5]
 [0.5]
 [0.5]
 [0.5]]
Output After Training:
[[0.5]
 [0.5]
 [0.5]
 [0.5]]
Output After Training:
[[0.5]
 [0.5]
 [0.5]
 [0.5]]
Output After Training:
[[0.5]
 [0.5]
 [0.5]
 [0.5]]
Output After Training:
[[0.5]
 [0.5]
 [0.5]
 [0.5]]
Output After Training:
[[0.5]
 [0.5]
 [0.5]
 [0.5]]
Output After Training:
[[0.5]
 [0.5]
 [0.5]
 [0.5]]
Output After Training:
[[0.5]
 [0.5]
 [0.5]
 [0.5]]
Output After Training:
[[0.5]
 [0.5]
 [0.5]
 [0.5]]
Output After Training:
[[0.5]
 [0.5]
 [0.5]
 [0.5]]
Output After Training:
[[0.5]
 [0.5]
 [0.5]
 [0.5]]
Output After Training:
[[0.5]
 [0.5]
 [0.5]
 [0.5]]
Output After Training:
[[0.5]
 [0.5]
 [0.5]
 [0.5]]
Output After Training:
[[0.5]
 [0.5]
 [0.5]
 [0.5]]
Output After

 [0.5]]
Output After Training:
[[0.5]
 [0.5]
 [0.5]
 [0.5]]
Output After Training:
[[0.5]
 [0.5]
 [0.5]
 [0.5]]
Output After Training:
[[0.5]
 [0.5]
 [0.5]
 [0.5]]
Output After Training:
[[0.5]
 [0.5]
 [0.5]
 [0.5]]
Output After Training:
[[0.5]
 [0.5]
 [0.5]
 [0.5]]
Output After Training:
[[0.5]
 [0.5]
 [0.5]
 [0.5]]
Output After Training:
[[0.5]
 [0.5]
 [0.5]
 [0.5]]
Output After Training:
[[0.5]
 [0.5]
 [0.5]
 [0.5]]
Output After Training:
[[0.5]
 [0.5]
 [0.5]
 [0.5]]
Output After Training:
[[0.5]
 [0.5]
 [0.5]
 [0.5]]
Output After Training:
[[0.5]
 [0.5]
 [0.5]
 [0.5]]
Output After Training:
[[0.5]
 [0.5]
 [0.5]
 [0.5]]
Output After Training:
[[0.5]
 [0.5]
 [0.5]
 [0.5]]
Output After Training:
[[0.5]
 [0.5]
 [0.5]
 [0.5]]
Output After Training:
[[0.5]
 [0.5]
 [0.5]
 [0.5]]
Output After Training:
[[0.5]
 [0.5]
 [0.5]
 [0.5]]
Output After Training:
[[0.5]
 [0.5]
 [0.5]
 [0.5]]
Output After Training:
[[0.5]
 [0.5]
 [0.5]
 [0.5]]
Output After Training:
[[0.5]
 [0.5]
 [0.5]
 [0.5]]
Outp