In [3]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import Imputer
from sklearn.model_selection import train_test_split
from sklearn.model_selection import KFold
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

dataset = pd.read_csv("G:\\UIT BS-SE Semester-VI Course Folders\\CS 321 - Artificial Intelligence\\Lab\\A.I. lab 07\\dermatology.data");
array = dataset.values
x = array[:,0:32];
y = array[:,32];
t_size = 0.70;

imp = Imputer(missing_values=np.nan, strategy="mean")
X = imp.fit_transform(x)
Y = y.reshape(-1,1)
Y = imp.fit_transform(Y)
Y = Y.reshape(-1)

X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size=t_size);

knn = KNeighborsClassifier(n_neighbors=20);
knn.fit(X_train,Y_train);

predictions = knn.predict(X_test);
print("\nAccuracy Score:",accuracy_score(Y_test, predictions))
print("\nConfusion Matrix:",confusion_matrix(Y_test, predictions))
print(classification_report(Y_test, predictions))

kfold = KFold(10, True, 1)
# enumerate splits
for train, test in kfold.split(dataset):
    np.set_printoptions(precision=3)
    print('X_train: %s, X_test: %s' % (X_train, X_test))
    print('Y_train: %s, Y_test: %s' % (Y_train, Y_test))
   
   




Accuracy Score: 0.921875

Confusion Matrix: [[200   0   0   0]
 [  2   0   0   0]
 [  3   0   0  15]
 [  0   0   0  36]]
             precision    recall  f1-score   support

        0.0       0.98      1.00      0.99       200
        1.0       0.00      0.00      0.00         2
        2.0       0.00      0.00      0.00        18
        3.0       0.71      1.00      0.83        36

avg / total       0.86      0.92      0.89       256

X_train: [[1. 1. 1. ... 0. 0. 2.]
 [2. 2. 2. ... 0. 0. 2.]
 [3. 3. 3. ... 0. 0. 1.]
 ...
 [2. 0. 1. ... 0. 0. 2.]
 [2. 2. 1. ... 0. 0. 2.]
 [1. 2. 2. ... 0. 0. 2.]], X_test: [[2. 1. 1. ... 0. 1. 1.]
 [2. 2. 2. ... 2. 2. 2.]
 [2. 2. 2. ... 0. 0. 2.]
 ...
 [2. 2. 0. ... 1. 0. 2.]
 [2. 2. 3. ... 0. 0. 2.]
 [2. 2. 0. ... 2. 2. 2.]]
Y_train: [0. 2. 0. 3. 3. 0. 0. 0. 3. 3. 0. 0. 0. 0. 0. 3. 0. 0. 0. 0. 0. 0. 0. 3.
 0. 3. 0. 2. 3. 0. 0. 0. 0. 0. 3. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 3. 0. 3. 3. 0. 0. 3. 3. 0. 0. 0. 0. 0. 2. 0. 0. 0. 0. 0.

D:\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


###